### ISSUE TITLE
Brackets don't match

### ISSUE THREAD

**Issue by charmoniumQ** [ctuning/ck-artifact-evaluation#7]
The bracket on `wfe/artifact-evaluation/templates/ae.tex:44` ([permalink](https://github.com/ctuning/ck-artifact-evaluation/blob/7ff374266f37472d16e5ed406d1f4feb7bfce548/wfe/artifact-evaluation/templates/ae.tex#L44)) is not closed. Is this intentional?

**Comment by gfursin** [comment]
Thank you for noticing that @charmoniumQ! It's a bug, not a feature ;) . I believe I've fixed that - is it working? Thanks a lot!!!

**Comment by charmoniumQ** [comment]
Thanks for the quick response :+1:
